# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 601b35425dd70a06887562556ab5c0ae006cf23763ae653e45cf430bb8e55a26a221ac7afaa6a79357916f695088e873695037f25710d3a46b62d362e4b546d1

test:
  secret_key_base: 78858dc022cafeb49e93fc30b61d96e4f8678eede3e57d663fa44e2ae37a89411e926927e03d49d21dfbc39871e5b3a20c8030f54ae951f10ebba48d22aed84e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
